---
output:
  pdf_document: default
  html_document: default
---
#Gavin Work

```{r}
#Loading libraries
library(ggplot2)
library(reshape2)
library(readr)
library(dplyr)

```



```{r}
#Load the commodity dataset
HGP <- read.csv("Feed Grains Yearbook Tables-All Years.csv")

```

```{r}
str(HGP)

summary(HGP)

head(HGP)

NewNames <- c("variable","Year","Planted.Acres","Harvested.Acres","value","Yield","Farm.Price","1","2")

names(HGP) <- NewNames

```
```{r}
#Removing  unnecessary information

HGP = subset(HGP, select = -c(3,4,6,7,8,9) )

HGP$Year <- gsub("/.*", "", HGP$Year)

HGP = filter(HGP, Year > 1974)

HGP = filter(HGP, variable == 'Corn')

HGP$Year <- as.numeric(substring(HGP$Year, 1, 4))
HGP$value <- as.numeric(gsub(",", "", HGP$value))

head(HGP)
```


```{r}
#plotting commodity prices over the years
ggplot(HGP, aes(x = Year, y = value))+
  geom_line()
```

```{r}
#Merging datasets

Corn.Production = bind_rows(HGP, melted_data)

Corn_Production_Cheese <- bind_rows(HGP, melted_data_cheese)
Corn_Production_Dry <- bind_rows(HGP, melted_data_dry_products)
Corn_Production_Evaporated <- bind_rows(HGP, melted_data_Evaporated_Condensed_Milk)
Corn_Production_Frozen <- bind_rows(HGP, melted_data_Frozen_products)
```


```{r}
#Creating graphs for Corn Production
ggplot(Corn_Production_Cheese, aes(x = Year, y = log(value) , color = variable)) +
  geom_step()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  labs(title = "Relation of Corn Production and Cheese consumption")
ggsave("Corn_Production_Cheese.jpeg")

ggplot(Corn_Production_Dry, aes(x = Year, y = log(value) , color = variable)) +
  geom_step()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  labs(title = "Relation of Corn Production and Dry products consumption")
ggsave("Corn_Production_Dry.jpeg")

ggplot(Corn_Production_Evaporated, aes(x = Year, y = log(value) , color = variable)) +
  geom_step()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  labs(title = "Relation of Corn Production and Evaporated and Condensed milk consumption")
ggsave("Corn_Production_Evaporated.jpeg")

ggplot(Corn_Production_Frozen, aes(x = Year, y = log(value) , color = variable)) +
  geom_step()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  labs(title = "Relation of Corn Production and Frozen products consumption")
ggsave("Corn_Production_Frozen.jpeg")

```


```{r}
#Loading in Milk Production Factors

MPF <- read.csv("annualmilkprodfactors.csv")

```





